"""Build the dependency-free Revolio portfolio. Run: python build.py"""
from pathlib import Path
import json,html

ROOT=Path(__file__).parent
DIST=ROOT/'dist'
P=json.loads((ROOT/'projects.json').read_text(encoding='utf-8'))
by_slug={p['slug']:p for p in P}
def e(s): return html.escape(str(s),quote=True)
def external(label,url,cls='pill'):
    return f'<a class="{cls}" href="{e(url)}" target="_blank" rel="noopener noreferrer">{e(label)}<span class="sr-only"> (opens in a new tab)</span></a>'
def header(active=''):
    links=[('Work','/work/','work'),('Studio','/#studio','studio'),('Our world','/world/','world')]
    nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if active==key else '')+f'>{label}</a>' for label,url,key in links)
    return '<a class="skip" href="#main">Skip to content</a><div class="wrap"><header class="site-header"><a class="logo" href="/" aria-label="Revolio home"><span class="brand-mark"><img src="/assets/revolio-mark.png" alt="" width="1011" height="1200"></span><span class="brand-name">REVOLIO<small>CREATIVE STUDIO</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button><nav class="nav" id="main-nav" aria-label="Main navigation">'+nav+'<a class="pill dark" href="/contact/">Start a conversation</a></nav></header></div>'
def contact():
    return '<section class="contact"><div class="wrap contact-row"><div><p class="eyebrow">Have something in mind?</p><h2>Let’s make<br>it matter.</h2></div><div><p>A launch, a series, a story that hasn’t found its shape yet. Tell us what you’re thinking.</p><a class="email" href="mailto:info@revolio.in">info@revolio.in</a><div class="contact-links"><a class="pill dark" href="/contact/">Start a project</a>'+external('Find us on Instagram','https://www.instagram.com/revoliomedia/','pill')+'</div></div></div></section>'
def footer():
    return '<footer class="site-footer wrap"><div class="footer-top"><a class="logo" href="/" aria-label="Revolio home"><span class="brand-mark"><img src="/assets/revolio-mark.png" alt="" width="1011" height="1200"></span><span class="brand-name">REVOLIO<small>CREATIVE STUDIO</small></span></a><div class="footer-links">'+external('Studio Instagram','https://www.instagram.com/revoliomedia/','')+external('Revolio Mag','https://www.instagram.com/revoliomag/','')+external('Dumb Biryani','https://www.instagram.com/dumbbbiryani/','')+'</div></div><div class="footer-bottom"><span>© 2026 Revolio Media</span><span>Good stories travel.</span><a href="/privacy/">Privacy</a></div></footer>'
def page(path,title,description,body,active='',with_contact=True):
    out=DIST/path;out.parent.mkdir(parents=True,exist_ok=True)
    favicon='/favicon.svg?v=2'
    doc=f'<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} — Revolio</title><meta name="description" content="{e(description)}"><meta name="theme-color" content="#009cff"><meta property="og:title" content="{e(title)} — Revolio"><meta property="og:description" content="{e(description)}"><meta property="og:type" content="website"><link rel="icon" type="image/svg+xml" sizes="any" href="{favicon}"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/details.css"><script src="/app.js" defer></script></head><body>{header(active)}<main id="main">{body}{contact() if with_contact else ""}</main>{footer()}</body></html>'
    out.write_text(doc,encoding='utf-8')
def card(p):
    return f'<a class="project-card reveal" data-category="{e(p["category"])}" href="/work/{p["slug"]}/"><div class="project-image"><img src="/assets/{p["image"]}.webp" alt="{e(p["name"])} — project imagery" loading="lazy" width="1000" height="606"><span class="view">Explore project</span></div><div class="project-info"><div><h3>{e(p["name"])}</h3><p>{e(p["client"])}</p></div><span>{e(p["category"])}</span></div></a>'
def cards(slugs): return ''.join(card(by_slug[s]) for s in slugs)
hero='''<section class="hero wrap"><div class="hero-meta"><p class="eyebrow">Independent minds. Internet-first ideas.</p><p class="eyebrow">Strategy / Production / Storytelling</p></div><h1>Ideas that earn<br>their <span class="blue">audience.</span></h1><div class="hero-bottom"><p class="hero-copy">We make films, build shows, and find the stories people want to spend time with. For brands. For culture. For the love of a good idea.</p><div class="hero-links"><a class="pill dark" href="/work/">Explore our work</a><a class="pill" href="#studio">Meet the studio</a></div></div><div class="hero-reel"><a class="reel-tile" href="/work/only-fridays/"><img src="/assets/cred.webp" alt="A chef-led dining experience from CRED Only Fridays" fetchpriority="high" width="1300" height="515"><span class="caption">CRED <small>Only Fridays</small></span></a><a class="reel-tile" href="/work/dumb-biryani/"><img src="/assets/dumb-biryani.webp" alt="Arhaan Khan, Dev Raiyani and Arush Verma on Dumb Biryani" width="1270" height="735"><span class="caption">Dumb Biryani <small>A Revolio original</small></span></a><a class="reel-tile" href="/work/rolling-loud/"><img src="/assets/rolling-loud.webp" alt="Live performance at Rolling Loud India" width="1080" height="530"><span class="caption">Rolling Loud <small>On the ground</small></span></a></div></section><div class="rail" aria-hidden="true"><span>Culture in the thinking.</span><i class="rotating">✳</i><span>Craft in the making.</span><i class="rotating">✳</i><span>Revolio in the credits.</span></div>'''
homework='<section class="section wrap" id="selected-work"><div class="section-top reveal"><div><p class="eyebrow">01 / Selected work</p><h2>Different briefs.<br>Distinct worlds.</h2></div><p>A few ways we’ve turned a brand’s point of view into something worth watching.</p></div><div class="work-grid">'+cards(['district-culture','only-fridays','in-dyou-time','rolling-loud','journeys-of-aspiration','hold-my-popcorn'])+'</div><div class="section-end"><a class="pill" href="/work/">Explore the full work index</a></div></section>'
studio='''<section class="section dark-section" id="studio"><div class="wrap"><div class="about-grid reveal"><p class="eyebrow">02 / The studio</p><div><h2 class="about-statement">The internet doesn’t owe<br>anyone its attention.<br><em>We make the effort to earn it.</em></h2><p class="about-support">Revolio sits at the intersection of production, marketing, and storytelling. We build internet-first content IPs for brands, from the first creative question to the way the finished work meets its audience.</p></div></div><div class="services"><article class="service reveal"><p class="eyebrow">01 / Find the idea</p><h3>Strategy &amp; concepts</h3><p>Find the audience, the cultural context, and the reason to care. Shape a point of view that can become a campaign, an editorial voice, or a repeatable show.</p></article><article class="service reveal"><p class="eyebrow">02 / Make it real</p><h3>Production &amp; craft</h3><p>Build the world around the idea. Visual identity, direction, production, and edits that hold the story together, in the studio or out on the ground.</p></article><article class="service reveal"><p class="eyebrow">03 / Give it a life</p><h3>Editorial &amp; distribution</h3><p>Think beyond a single upload. Develop platform-specific stories, cutdowns, and ongoing editorial formats that give people a reason to return.</p></article></div></div></section>'''
world_cards='<div class="worlds"><article class="world-card mag reveal"><p class="eyebrow">Our independent magazine</p><h3>Revolio<br>Mag.</h3><p>For the observations that turn into a longer conversation. Our perspective on culture, the internet, and the ways we live now.</p><a class="pill" href="/world/#magazine">Enter the magazine</a></article><article class="world-card original reveal"><img src="/assets/dumb-biryani.webp" alt="The cast of Dumb Biryani" loading="lazy"><p class="eyebrow">A Revolio original</p><h3>Dumb<br>Biryani.</h3><p>A little chaotic. Entirely its own thing. An internet-first reality show that turns the podcast format on its head.</p><a class="pill" href="/work/dumb-biryani/">Meet the original</a></article></div>'
world='<section class="section wrap"><div class="section-top reveal"><div><p class="eyebrow">03 / Our world</p><h2>Some ideas<br>start with us.</h2></div><p>Alongside client work, we make space for our own questions, voices, and experiments.</p></div>'+world_cards+'</section>'
clients='<section class="clients wrap"><p class="eyebrow">A few of the brands in our story</p><div class="client-list"><span>CRED</span><span>Netflix</span><span>Zomato</span><span>Prime Video</span><span>District</span><span>Aspora</span><span>d’you</span><span>Capri</span><span>COSMIX</span><span>SuperYou</span></div></section>'
page('index.html','Ideas that earn their audience','Revolio is a creative studio building internet-first films, series and content for brands. Explore our work, original shows and magazine.',hero+homework+studio+world+clients)

filters=''.join(f'<button class="filter" data-filter="{c}" aria-pressed="{str(c=="All").lower()}">{c}</button>' for c in ['All','Films','Series','Editorial','Live culture','Originals','Archive'])
feed='<section class="section wrap feed-section"><div class="section-top"><div><p class="eyebrow">From the studio feed</p><h2>More where<br>that came from.</h2></div><p>Short films, experiments, and a look behind the work. Open the original posts on Instagram.</p></div><div class="feed-list">'+''.join(external(title,url,'feed-item') for title,url in [('Anuj × Revolio — written and directed by Aditya Shekhawat','https://www.instagram.com/anuj.mp4/reel/DXbz7WUjOnc/'),('Side Quests / Episode 2 — A floater in the sky','https://www.instagram.com/sidestquests/reel/DShNyZVjLU-/'),('Side Quests / Episode 1 — A new sigma influencer is born','https://www.instagram.com/sidestquests/reel/DPWWqDXEV4q/'),('Rewind — on set with CRED, Sparx, Dumb Biryani and more','https://www.instagram.com/revoliomedia/p/C9zqv3gyuHC/'),('The 2024 work recap','https://www.instagram.com/revoliomedia/reel/DD4WPUnS0tE/')])+'</div></section>'
work='<section class="page-intro wrap"><p class="eyebrow">The work index</p><h1>See what<br>we’re about.</h1><p>Films, shows, editorial worlds, and stories from the ground. Explore the ideas and the work behind them.</p></section><section class="wrap" style="padding-bottom:50px"><div class="filter-bar" role="group" aria-label="Filter projects">'+filters+f'</div><p class="work-count" role="status" aria-live="polite">{len(P)} projects</p><div class="work-grid">'+''.join(card(p) for p in P)+'</div></section>'+feed
page('work/index.html','Work','Explore Revolio’s client work and original formats: District, CRED, Aspora, d’you, Rolling Loud, Prime Video and more.',work,'work')
for i,p in enumerate(P):
    links=''.join(external(label,url) for label,url in p['links'])
    detail=f'<section class="page-intro wrap"><a class="eyebrow quiet-link" href="/work/">Work index</a><p class="eyebrow" style="margin-top:35px">{e(p["client"])} / {e(p["name"])}</p><h1 class="case-title">{e(p["title"])}</h1><p>{e(p["intro"])}</p></section><div class="wrap"><div class="detail-image"><img src="/assets/{p["image"]}.webp" alt="{e(p["name"])} — project imagery" width="1400" height="800"></div><section class="case-content"><aside class="case-meta"><div><span class="eyebrow">Client / Platform</span>{e(p["client"])}</div><div><span class="eyebrow">The work</span>{e(p["services"])}</div></aside><div class="story"><h2>The idea in practice.</h2>'+''.join(f'<p>{e(s)}</p>' for s in p['paragraphs'])+f'<div class="insight">{e(p["insight"])}</div>'+('<div class="case-links">'+links+'</div>' if links else '')+'</div></section></div>'
    nxt=P[(i+1)%len(P)]
    detail+=f'<section class="next-project wrap"><span class="eyebrow">Keep exploring</span><a href="/work/{nxt["slug"]}/">{e(nxt["name"])}</a></section>'
    page(f'work/{p["slug"]}/index.html',p['name'],p['intro'],detail,'work')

worldbody='''<section class="page-intro wrap"><p class="eyebrow">The Revolio universe</p><h1>Curiosity doesn’t<br>need a brief.</h1><p>Our magazine and original series are where our own questions become things you can read, watch, and come back to.</p></section><section class="section wrap" id="magazine"><div class="mag-feature"><div class="editorial-cover reveal"><p class="eyebrow">Independent culture &amp; commentary</p><span class="mag-word">REVOLIO<br>MAG.</span><p>Making dinner-table conversations<br>more interesting.</p></div><div class="reveal"><p class="eyebrow" style="margin-bottom:20px">01 / Revolio Mag</p><h2>Stay curious.<br>Bring a point of view.</h2><p>Culture doesn’t stop at the headline. Revolio Mag looks at what the internet reveals about us, and what happens when private habits become public conversations.</p>'''+external('Read the magazine','https://revoliomag.substack.com/')+' '+external('Follow @revoliomag','https://www.instagram.com/revoliomag/')+'''</div></div><article class="essay reveal"><p class="eyebrow">From the magazine / 14 September 2026</p><h3>Why Is Everyone Recording<br>Themselves Crying?</h3><p>Revolio Mag and Manya Lohita Ahuja explore why private emotion becomes something we document, watch, and share.</p>'''+external('Read the essay','https://revoliomag.substack.com/p/why-is-everyone-recording-themselves','quiet-link')+'''</article></section><section class="section dark-section"><div class="wrap"><div class="section-top"><div><p class="eyebrow">02 / Revolio Originals</p><h2>Enter Dumb Biryani.</h2></div><p style="color:#bbbcb6">Arhaan Khan. Dev Raiyani. Arush Verma. A reality show with its own rules.</p></div><a href="/work/dumb-biryani/" class="original-wide"><img src="/assets/dumb-biryani.webp" alt="Arhaan Khan, Dev Raiyani and Arush Verma in Dumb Biryani" loading="lazy"></a><div class="original-bottom"><p>Built end to end by Revolio, from its lo-fi visual world to a food-truck launch on the streets of Mumbai.</p><div>'''+external('Watch the show','https://www.youtube.com/@dumbbbiryani','pill blue')+''' <a href="/work/dumb-biryani/" class="pill light">Behind the idea</a></div></div><div class="episode"><span class="eyebrow">From the channel</span><h3>24 hours in Greece, featuring Malaika.</h3>'''+external('Watch the episode','https://youtu.be/bkgaR1XfGG4','quiet-link')+'''</div></div></section>'''
page('world/index.html','Our world','Explore Revolio Mag, our independent culture publication, and Dumb Biryani, a Revolio original series.',worldbody,'world')

contactbody='''<section class="page-intro wrap"><p class="eyebrow">Let’s start with a conversation</p><h1>What are<br>you thinking?</h1><p>Tell us what you’re making, who it’s for, and where you want it to go. An early idea is a perfectly good place to start.</p></section><section class="wrap contact-page"><a class="email-link" href="mailto:info@revolio.in">info@revolio.in</a><form class="contact-form" id="brief-form"><div class="form-grid"><div class="field"><label for="name">Your name *</label><input id="name" name="name" autocomplete="name" required maxlength="120"></div><div class="field"><label for="email">Email address *</label><input id="email" name="email" autocomplete="email" type="email" required maxlength="180"></div><div class="field"><label for="company">Company / organisation</label><input id="company" name="company" autocomplete="organization" maxlength="160"></div><div class="field"><label for="service">What do you have in mind?</label><select id="service" name="service"><option>A new project</option>A film or campaign</option>A series or content IP</option> <option>Editorial and ongoing content</option><option>Event and on-ground coverage</option><option>An original or magazine collaboration</option><option>Something else</option></select></div></div><div class="field"><label for="brief">A little about the idea *</label><textarea id="brief" name="brief" placeholder="The idea, the audience, and any timing we should know about…" required maxlength="4000"></textarea></div><button class="pill dark" type="submit">Prepare email enquiry</button><p class="hint">We’ll prepare an email draft for you to review and send from your email app. This form doesn’t submit or store your details.</p><div class="form-feedback" id="form-result" hidden tabindex="-1"><p>Your draft is ready. Open it in your email app, review it, then send it when you’re ready.</p><a id="email-draft" class="pill blue" style="margin-top:16px" href="mailto:info@revolio.in">Open email draft</a></div></form><div class="direct-links"><p class="eyebrow">Prefer to explore first?</p><a class="quiet-link" href="/work/">Browse the work</a>'''+external('Visit the studio on Instagram','https://www.instagram.com/revoliomedia/','quiet-link')+'''</div></section>'''
page('contact/index.html','Start a conversation','Contact Revolio about a film, campaign, content series, editorial project or original collaboration.',contactbody,'',False)
privacy='''<section class="page-intro wrap"><p class="eyebrow">A straightforward note</p><h1>Your privacy.</h1></section><section class="wrap privacy-copy"><h2>Project enquiries</h2><p>The enquiry form prepares an email draft on your device. It does not submit information to a form service or save your details in this website. If you choose to send the email, your email provider delivers it to info@revolio.in.</p><h2>Browsing this site</h2><p>This website does not add advertising trackers, analytics scripts, or browser storage. Our hosting provider may process technical information needed to serve and secure the site, including sign-in information for private access.</p><h2>External services</h2><p>Instagram, YouTube, and Substack links open those services in another tab. Their own privacy terms apply. Fonts are requested from Google Fonts when you load a page.</p><h2>Contact</h2><p>For questions about information you share with Revolio, email <a class="quiet-link" href="mailto:info@revolio.in">info@revolio.in</a>.</p></section>'''
page('privacy/index.html','Privacy','How this Revolio website handles enquiries and external services.',privacy,'',False)
page('404.html','Page not found','Find your way back to Revolio.', '<section class="page-intro wrap error-page"><p class="eyebrow">404 / Lost in the edit</p><h1>A different<br>kind of cut.</h1><p>This page isn’t here. There’s plenty of work to explore.</p><a class="pill dark" style="margin-top:30px" href="/work/">Back to the work</a></section>','',False)
print(f'Generated {len(P)+6} pages from {len(P)} project records.')
