from pathlib import Path
import json,html
ROOT=Path(__file__).parent; DIST=ROOT/'dist'
P=json.loads((ROOT/'projects.json').read_text(encoding='utf-8')); by_slug={p['slug']:p for p in P}
V=json.loads((ROOT/'clips.json').read_text(encoding='utf-8')) if (ROOT/'clips.json').exists() else []
def e(s):return html.escape(str(s),quote=True)
def ext(label,url,cls='text-link'):
 return f'<a class="{cls}" href="{e(url)}" target="_blank" rel="noopener noreferrer">{e(label)}<span class="sr-only"> (opens in a new tab)</span></a>'
def brand():return '<a class="brand" href="/" aria-label="Revolio home"><img src="/assets/revolio-mark.png" alt="" width="1011" height="1200"><span class="brand-label"><strong>revolio</strong><small>Creative studio</small></span></a>'
def header(active=''):
 nav=''.join(f'<a href="{u}"'+(' aria-current="page"' if k==active else '')+f'>{s}</a>' for s,u,k in [('The work','/work/','work'),('In motion','/watch/','watch'),('The studio','/#studio','studio'),('Our world','/world/','world')])
 return '<a class="skip" href="#main">Skip to content</a><header class="site-nav shell">'+brand()+'<button class="menu-btn" aria-expanded="false" aria-controls="navigation">Menu</button><nav class="navigation" id="navigation" aria-label="Main navigation">'+nav+'<a class="nav-contact" href="/contact/">Got a good one?</a></nav></header>'
def footer():
 return '<footer class="footer"><div class="shell"><div class="footer-top">'+brand()+'<div class="footer-socials">'+ext('The studio','https://www.instagram.com/revoliomedia/','')+ext('Revolio Mag','https://www.instagram.com/revoliomag/','')+ext('Dumb Biryani','https://www.instagram.com/dumbbbiryani/','')+'</div></div><div class="footer-bottom"><span>© 2026 Revolio Media</span><span>Stay curious. Make something.</span><a href="/privacy/">Privacy</a></div></div></footer>'
def cta():return '<section class="project-cta"><div class="shell"><div class="cta-top"><p class="eyebrow">An idea. A question. A wonderfully weird brief.</p><p class="eyebrow">We’re listening.</p></div><h2>Let’s make<br><em>something happen.</em></h2><div class="cta-bottom"><p>Bring us the thing you can’t stop thinking about. We’ll figure out what it could become.</p><a class="text-link" href="/contact/">Start the conversation <span class="plus" aria-hidden="true">+</span></a></div></div></section>'
def page(path,title,description,body,active='',tone='',with_cta=True):
 out=DIST/path;out.parent.mkdir(parents=True,exist_ok=True)
 out.write_text(f'<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolio Media - Creative Studio</title><meta name="description" content="{e(description)}"><meta name="theme-color" content="#1a1a18"><meta property="og:title" content="{e(title)} — Revolio"><meta property="og:description" content="{e(description)}"><link rel="icon" type="image/svg+xml" href="/favicon.svg?v=3"><link rel="stylesheet" href="/revolio.css"><link rel="stylesheet" href="/watch.css"><script src="/experience.js" defer></script><script src="/watch.js" defer></script></head><body class="{tone}">{header(active)}<main id="main">{body}{cta() if with_cta else ""}</main>{footer()}</body></html>',encoding='utf-8')
def card(p,index=0):
 shape='portrait' if p['height']>p['width'] else 'landscape'
 return f'<a class="project-card {shape} reveal" data-category="{e(p["category"])}" href="/work/{p["slug"]}/"><div class="project-visual"><img src="/assets/{p["image"]}.webp" width="{p["width"]}" height="{p["height"]}" alt="{e(p["name"])} — full project image" loading="lazy"></div><div class="project-meta"><div><h3>{e(p["name"])}</h3><p>{e(p["client"])} / {e(p["category"])}</p></div><span class="project-num" aria-hidden="true">{index+1:02d}</span></div></a>'
def film_card(v):
 kind=v.get('type','video');ratio=f'{v["width"]}/{v["height"]}';name=e(v['title'])
 attrs=f'data-title="{name}" data-kind="{kind}" data-client="{e(v["client"])}" data-user-paused="false"'
 if kind=='image':
  slides=v['slides'];attrs+=' data-slides="'+e(json.dumps(slides))+'"'
  media=f'<img class="film-image" src="{e(slides[0]["image"])}" alt="{name} ? image 1" width="{slides[0]["width"]}" height="{slides[0]["height"]}" loading="lazy">'
  controls='<div class="slide-controls"><button data-frame-prev aria-label="Previous image">Prev</button><span data-frame-count>1 / '+str(len(slides))+'</span><button data-frame-next aria-label="Next image">Next</button></div>'
 else:
  audio=v.get('has_audio',True);attrs+=' data-audio="'+str(audio).lower()+'"'
  variants=v.get('variants',[])
  if variants:attrs+=' data-variants="'+e(json.dumps(variants))+'"'
  media=f'<video muted {"" if variants else "loop"} playsinline preload="none" poster="{e(v["poster"])}" data-src="{e(v["video"])}" width="{v["width"]}" height="{v["height"]}" aria-label="{name}"></video><span class="film-audio-state" aria-hidden="true">Sound on</span><p class="film-error" hidden>Video unavailable here. Watch the original below.</p>'
  controls=f'<div class="film-controls"><button type="button" data-film-play aria-label="Play {name}">Play</button><button type="button" data-film-sound aria-pressed="false" aria-label="Toggle sound for {name}"'+(' disabled' if not audio else '')+'>'+('Sound on' if audio else 'Silent')+'</button></div>'
  if variants:controls+='<div class="variant-controls"><button data-variant-prev aria-label="Previous animation">Prev</button><span data-variant-count>1 / '+str(len(variants))+'</span><button data-variant-next aria-label="Next animation">Next</button></div>'
 project=f'<a href="{e(v["project"])}" class="text-link">The project</a>' if v.get('project') else ''
 return f'<article class="film-card" {attrs}><div class="film-screen" style="--frame-ratio:{ratio}">'+media+controls+f'</div><div class="film-meta"><p class="eyebrow">{e(v["client"])}</p><h3>{name}</h3><p>{e(v["caption"])}</p><div class="film-links">'+ext('Original post',v['source'])+project+'</div></div></article>'

def video_gallery(homepage=False):
 if not V:return ''
 title='Better in <em>motion.</em>' if homepage else 'Less explaining.<br><em>More watching.</em>'
 tag='h2' if homepage else 'h1'
 collection=sorted([v for v in V if v.get('featured')],key=lambda v:v.get('featured_order',99)) if homepage else V
 clients=list(dict.fromkeys(['All']+[v['client'] for v in V]))
 filters='' if homepage else '<div class="watch-filters" role="group" aria-label="Filter the screening room">'+''.join('<button data-watch-filter="'+e(c)+'" aria-pressed="'+str(c=='All').lower()+'">'+e(c)+'</button>' for c in clients)+'</div><p class="watch-count" role="status" aria-live="polite">'+str(len(V))+' pieces</p>'
 return '<section class="watch-section '+('home-watch' if homepage else '')+'"><div class="shell"><div class="watch-heading"><div><p class="eyebrow">The screening room</p><'+tag+'>'+title+'</'+tag+'></div></div>'+filters+'<div class="film-grid '+('featured-films' if homepage else '')+'">'+''.join(film_card(v) for v in collection)+'</div>'+('<a href="/watch/" class="text-link watch-more">Open the screening room <span class="plus" aria-hidden="true">+</span></a>' if homepage else '')+'</div></section>'

def home():
 picks=['dumb-biryani','district-films','only-fridays','first-time-with-simba','in-dyou-time','test']
 scenes=''
 for i,slug in enumerate(picks):
  p=by_slug[slug];ims=p['gallery'][:2] if slug=='district-films' else [p['image']]
  scenes+=f'<a class="scene {"active" if i==0 else ""} {"duo" if len(ims)==2 else ""}" href="/work/{slug}/" data-name="{e(p["name"])}" data-client="{e(p["client"])} / {e(p["category"])}" aria-label="Explore {e(p["name"])}" aria-hidden="{str(i!=0).lower()}"'+(' tabindex="-1"' if i else '')+'>'+''.join(f'<img src="/assets/{im}.webp" alt="{e(p["name"])} — full frame">' for im in ims)+'</a>'
 selectors=''.join(f'<button type="button" data-scene="{i}" aria-label="Show {e(by_slug[s]["name"])}" aria-pressed="{str(i==0).lower()}">{i+1:02d}</button>' for i,s in enumerate(picks))
 hero='<section class="studio-hero shell"><div class="hero-topline"><p class="eyebrow">Independent minds. A very public imagination.</p><p class="eyebrow">Revolio / Creative studio</p></div><div class="hero-composition"><div class="hero-type"><span class="small-note" aria-hidden="true">For the plot.</span><h1><span class="hero-line">We make</span><em><span>a</span><span>scene.</span></em></h1><p class="hero-copy">Films you lean into. Shows you come back for. Brands with something to say.</p><a href="/work/" class="text-link">See what we make <span class="plus" aria-hidden="true">+</span></a></div><div><div class="screening"><span class="vertical-label">A little less ordinary</span><div class="screen-top"><span>On our screen</span><span class="screen-pips" aria-hidden="true"><i></i><i></i><i></i></span><span id="scene-counter">01 / 06</span></div><div class="screen-stage" aria-label="Selected project reel">'+scenes+'</div><div class="screen-caption"><div aria-live="polite"><strong id="scene-name">Dumb Biryani</strong><span class="project-type" id="scene-client">Revolio Originals / Originals</span></div><div class="screen-controls"><button id="scene-prev" aria-label="Previous project">PREV</button><button id="scene-next" aria-label="Next project">NEXT</button></div></div></div><div class="scene-selector" role="group" aria-label="Choose a project"><span>Change the scene</span>'+selectors+'</div></div></div><div class="hero-foot"><p>Creative thinking.<br>With the credits to match.</p><p class="disciplines">Strategy <span>/</span> Production <span>/</span> Original IPs <span>/</span> Editorial</p></div></section>'
 wall='<section class="work-section"><div class="shell"><div class="section-heading reveal"><div><p class="eyebrow">Out in the world</p><h2>Proof of<br><em>an imagination.</em></h2></div><p>Different worlds. Different rules. One question: why would someone want to watch?</p></div><div class="work-wall">'+''.join(card(by_slug[s],i) for i,s in enumerate(['district-films','test','only-fridays','in-dyou-time','the-sports-women','journeys-of-aspiration']))+'</div><div class="work-footer"><a href="/work/" class="text-link">There’s more where that came from <span class="plus" aria-hidden="true">+</span></a><button class="button" data-surprise>Surprise me</button></div></div></section>'
 studio='''<section class="manifesto shell" id="studio"><p class="eyebrow">A studio. A point of view.</p><div class="reveal"><h2>We’re interested in<br>what makes people<br><em>feel something.</em></h2><p>A laugh. A question. The urge to send it to someone. That’s where our work starts.</p><p>Revolio brings production, marketing, and storytelling into the same room. We build content worlds for brands—and a few of our own.</p></div></section><section class="method shell" aria-label="What we do"><details open><summary><span class="micro">01</span><h3>Find the thing worth saying.</h3></summary><p>Content strategy, cultural research, concepts, and show development. We find the point of view that gives a brand a reason to enter the conversation.</p></details><details><summary><span class="micro">02</span><h3>Give it a world to live in.</h3></summary><p>Visual identity, direction, production, and editing. From a studio set to the streets, the craft follows the idea and the people inside it.</p></details><details><summary><span class="micro">03</span><h3>Think past the first upload.</h3></summary><p>Editorial, social storytelling, and distribution. We shape formats that can grow across episodes, platforms, and the conversations they start.</p></details></section>'''
 worlds='''<section class="world-section"><div class="shell"><div class="section-heading"><div><p class="eyebrow">Not everything begins with a brief</p><h2 class="world-heading">Meanwhile,<br><em>in our heads.</em></h2></div><p>Our own questions become things you can read, watch, and get a little too invested in.</p></div><div class="world-panels"><article class="world-panel mag-panel reveal"><p class="eyebrow">Culture, with a point of view</p><h3>Revolio<br><em>Mag.</em></h3><p>Making dinner-table conversations more interesting.</p><a href="/world/#magazine" class="text-link">Read between the scrolls <span class="plus" aria-hidden="true">+</span></a></article><article class="world-panel db-panel reveal"><p class="eyebrow">A Revolio original</p><h3>Dumb Biryani.</h3><img class="db-still" src="/assets/dumb-biryani-full-0.webp" alt="Hello Brothers episode of Dumb Biryani, showing all guests" loading="lazy"><p>Three friends. A format with very few rules. A world that’s entirely its own.</p><a href="/work/dumb-biryani/" class="text-link">Get into it <span class="plus" aria-hidden="true">+</span></a></article></div></div></section>'''
 clients='<section class="client-section shell"><p class="eyebrow">Some of the company we keep</p><div class="client-names">'+''.join(f'<span>{x}</span>' for x in ['CRED','Netflix','District','Prime Video','Aspora','d’you','COSMIX','Capri','Zomato','SuperYou'])+'</div></section>'
 page('index.html','We make a scene','Revolio makes films, shows, editorial worlds, and original IPs. Independent creative thinking, with the credits to match.',hero+video_gallery(True)+wall+studio+worlds)
home()

def work():
 filters=''.join(f'<button class="filter" data-filter="{c}" aria-pressed="{str(c=="All").lower()}">{c}</button>' for c in ['All','Films','Series','Editorial','Live culture','Originals','Archive'])
 intro='<section class="page-intro shell"><p class="eyebrow">The work / Explore at your own pace</p><h1>Pick your<br><em>rabbit hole.</em></h1><p>Twenty different ways into the Revolio imagination. Films, formats, and a few things that don’t sit neatly in a box.</p></section>'
 wall='<section class="shell"><div class="portfolio-tools"><div class="filters" role="group" aria-label="Filter projects">'+filters+'</div><div class="view-switch" role="group" aria-label="Choose portfolio view"><button data-view="wall" aria-pressed="true">Wall</button><button data-view="index" aria-pressed="false">Index</button></div></div><p class="work-count" role="status" aria-live="polite">20 projects</p><div class="portfolio-wall">'+''.join(card(p,i) for i,p in enumerate(P))+'</div></section>'
 links=[('Anuj × Revolio — a short film by Aditya Shekhawat','https://www.instagram.com/anuj.mp4/reel/DXbz7WUjOnc/'),('Side Quests / A floater in the sky','https://www.instagram.com/sidestquests/reel/DShNyZVjLU-/'),('Side Quests / A new sigma influencer is born','https://www.instagram.com/sidestquests/reel/DPWWqDXEV4q/'),('Rewind / A look behind the work','https://www.instagram.com/revoliomedia/p/C9zqv3gyuHC/'),('Revolio / The 2024 work recap','https://www.instagram.com/revoliomedia/reel/DD4WPUnS0tE/')]
 feed='<section class="feed-section shell"><p class="eyebrow">Fresh from the studio feed</p><h2>The plot continues.</h2>'+''.join(ext(t,u,'feed-item') for t,u in links)+'</section>'
 page('work/index.html','The work','Explore Revolio’s films, original formats, editorial platforms, and client projects in a visual wall or a quick index.',intro+wall+feed,'work','on-dark')
work()

def cases():
 for i,p in enumerate(P):
  images=p['gallery'];kind='three' if len(images)>=3 else ('two' if len(images)==2 else 'one')
  heading=f'<section class="case-heading shell"><div class="breadcrumb"><a href="/work/">The work</a><span>{e(p["category"])}</span></div><h1>{e(p["name"])}</h1><p class="case-deck">{e(p["title"])}</p></section>'
  gallery=f'<div class="case-gallery {kind}">'+''.join(f'<img src="/assets/{im}.webp" alt="{e(p["name"])} — complete project frame {j+1}"'+(' loading="lazy"' if j else '')+'>' for j,im in enumerate(images))+'</div>'
  prose='<section class="case-story shell"><aside class="case-meta"><div><span class="eyebrow">Made with</span>'+e(p['client'])+'</div><div><span class="eyebrow">Our part</span>'+e(p['services'])+'</div></aside><div class="case-prose"><h2>Here’s the idea.</h2><p class="readable">'+e(p['intro'])+'</p>'+''.join('<p>'+e(s)+'</p>' for s in p['paragraphs'])+'<p class="insight">'+e(p['insight'])+'</p><div class="case-links">'+''.join(ext(t,u,'button') for t,u in p['links'])+'</div></div></section>'
  nxt=P[(i+1)%len(P)];nextlink=f'<section class="next-project shell"><p class="eyebrow">The next rabbit hole</p><a href="/work/{nxt["slug"]}/">{e(nxt["name"])} <span aria-hidden="true">+</span></a></section>'
  page(f'work/{p["slug"]}/index.html',p['name'],p['intro'],heading+gallery+prose+nextlink,'work')
cases()

def world():
 mast='<section class="world-mast shell" id="magazine"><p class="eyebrow">Culture / Curiosity / Our own corner of the internet</p><h1>Revolio <em>Mag.</em></h1><p>Making dinner-table conversations more interesting.</p></section>'
 editorial='<section class="editorial-grid shell"><div class="editor-note"><p class="eyebrow">A note from our world</p><h2>Less scrolling.<br>More wondering.</h2><p>What does the internet say about the way we live? What changes when private habits turn into public conversations? Our magazine follows the questions that stay with us.</p>'+ext('Read the magazine','https://revoliomag.substack.com/')+'<br>'+ext('Follow @revoliomag','https://www.instagram.com/revoliomag/')+'</div><article class="essay-card reveal"><p class="eyebrow">14 September 2026 / Internet culture</p><h3>Why Is Everyone Recording Themselves <em>Crying?</em></h3><p>Revolio Mag and Manya Lohita Ahuja explore why private emotion becomes something we document, watch, and share.</p>'+ext('Read the essay','https://revoliomag.substack.com/p/why-is-everyone-recording-themselves')+'</article></section>'
 original='<section class="original-section"><div class="shell"><p class="eyebrow">Meanwhile, on your screen / A Revolio original</p><h2>Dumb<br><em>Biryani.</em></h2><div class="original-layout"><img src="/assets/dumb-biryani-still.webp" alt="Arhaan Khan, Dev Raiyani and Arush Verma in Dumb Biryani" loading="lazy"><div><p>Arhaan Khan. Dev Raiyani. Arush Verma. An internet-first reality show that turns the podcast format into something of its own.</p><p>Built end to end by Revolio, from its lo-fi visual world to a food-truck launch on the streets of Mumbai.</p>'+ext('Watch the show','https://www.youtube.com/@dumbbbiryani')+'<br><a class="text-link" href="/work/dumb-biryani/">Behind the idea <span class="plus" aria-hidden="true">+</span></a></div></div><div class="episode"><div><p class="eyebrow">From the channel</p><h3>24 hours in Greece, featuring Malaika.</h3></div>'+ext('Watch this episode','https://youtu.be/bkgaR1XfGG4')+'</div></div></section>'
 page('world/index.html','Our world','Revolio Mag and Dumb Biryani. Independent editorial, original shows, and the questions that keep us making things.',mast+editorial+original,'world')
world()

def contact():
 intro='<section class="contact-intro shell"><div><p class="eyebrow">Let’s start somewhere interesting</p><h1>What’s<br><em>the plot?</em></h1></div><div><p>A film. A format. An idea that’s still a little hard to explain. Tell us what’s on your mind.</p><a href="mailto:info@revolio.in" class="email-address">info@revolio.in</a></div></section>'
 body='''<section class="contact-body shell"><aside class="contact-aside"><p>Good conversations make good starting points.</p><p>No polished brief required. Give us the audience, the ambition, and anything we should know.</p><a href="/work/" class="text-link">Explore first <span class="plus" aria-hidden="true">+</span></a></aside><form class="brief-form" id="brief-form"><div class="form-grid"><div class="field"><label for="name">Your name *</label><input id="name" name="name" autocomplete="name" required maxlength="120"></div><div class="field"><label for="email">Your email *</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="180"></div><div class="field"><label for="company">Company / organisation</label><input id="company" name="company" autocomplete="organization" maxlength="160"></div><div class="field"><label for="service">What are we making?</label><select id="service" name="service"><option>A new project</option><option>A film or campaign</option><option>A series or content IP</option><option>Editorial and ongoing content</option><option>Event and on-ground coverage</option><option>An original or magazine collaboration</option><option>Something else</option></select></div></div><div class="field"><label for="brief">Give us the opening scene. *</label><textarea id="brief" name="brief" required maxlength="4000" placeholder="The idea, the audience, and any timing we should know about…"></textarea></div><button type="submit" class="button solid">Prepare the email</button><p class="form-note">This prepares a draft in your email app for you to review and send. Your details aren’t submitted or stored by this form.</p><div id="form-result" class="form-feedback" hidden><p>Your draft is ready. Review it in your email app and send it when you’re ready.</p><a id="email-draft" class="button solid" href="mailto:info@revolio.in">Open email draft</a></div></form></section>'''
 page('contact/index.html','What’s the plot?','Start a project or a conversation with Revolio. Tell us about your film, content series, editorial project, or original idea.',intro+body,'','contact-page',False)
contact()
privacy='''<section class="page-intro paper shell"><p class="eyebrow">A straightforward note</p><h1>Your <em>privacy.</em></h1></section><section class="privacy-copy shell"><h2>Project enquiries</h2><p>The enquiry form prepares an email draft on your device. It does not submit information to a form service or store your details. If you send the email, your email provider delivers it to info@revolio.in.</p><h2>Browsing this site</h2><p>This website does not add advertising trackers, analytics scripts, or browser storage. Our hosting provider may process technical information needed to serve and secure the site, including sign-in information for private access.</p><h2>External services</h2><p>Instagram, YouTube, and Substack links open those services in another tab. Their own privacy terms apply. Fonts are requested from Google Fonts when you load a page.</p><h2>Contact</h2><p>For questions about information you share with Revolio, email <a class="text-link" href="mailto:info@revolio.in">info@revolio.in</a>.</p></section>'''
page('privacy/index.html','Privacy','How the Revolio website handles enquiries and external services.',privacy,with_cta=False)
page('404.html','Lost the plot?','Find your way back to the Revolio studio.','<section class="page-intro paper shell error-page"><p class="eyebrow">404 / An unexpected plot twist</p><h1>Lost<br><em>the plot?</em></h1><p>This page isn’t here. There’s plenty more to get into.</p><a class="text-link" href="/work/">Back to the work <span class="plus" aria-hidden="true">+</span></a></section>',with_cta=False)


page('watch/index.html','In motion','A watchable gallery of Revolio films and original work. Muted playback with hover-controlled sound.',video_gallery(),'watch','on-dark')

print('Built',len(list(DIST.rglob('*.html'))),'pages with',len(V),'screening-room entries.')
